baseurl = "/"
contentdir = "content"
publishdir = "public"

canonifyurls = true
relativeURLS = false

theme = "diary"
title = "Maximilian's writing"
languageCode = "vi-vn"
summaryLength = 42

copyright = "Maximilian de Cato, writing with love, 2024"

[author]
name = "Maximilian de Cato"

[params]
description = "My personal blog and academic info"
showFooterCredits = true
math = true
enableLaTeX = true
useIcon = true
enableReadingTime = true
googleSearchCode = "83a0b058839eb4182"

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss+xml"
baseName = "feed"

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 3

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[module]
  [module.hugoVersion]
    extended = true
    min = '0.111.0'
