#+Title: Ringo's blog
#+AUTHOR: Ringo Stark
#+DATE: \today
#+COMMENT: 

# #+SETUPFILE: "./assets/latex/report-main.org"

#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE: vi

#+EXCLUDE_TAGS: noexport

#+hugo_front_matter_format: yaml

#+hugo_auto_set_lastmod: t
#+hugo_base_dir: .
#+hugo_section: .

* Posts
:properties:
:export_hugo_section: posts
:end:

** Các tác vụ thông thường về text
:PROPERTIES:
:CREATED: [2023-08-20 Sun]
:export_file_name: hello
:EXPORT_DATE: 2024-04-13 Sat 21:38
:END:
Tất cả mọi thế giới của IT đều có thể quy về text, nên tác vụ text có vai trò lớn trong việc nâng cao năng suất.
*** Thay thế đoạn văn bản bị gãy dòng thành văn bản có dòng dài hơn, như tiêu chuẩn :shell:vim:
:PROPERTIES:
:CREATED: [2023-05-21 Sun 09:16]
:END:

#+BEGIN_SRC search and replace
SEARCH STRING: ((?:[^.?\n]$|\n(?!.?$)))\n
REPLACE STRING: $1
#+END_SRC

Lưu ý là có dấu cách " " ở cuối dòng replace string

EDITED: [2023-06-08 Thu 20:43]
Hoặc có thể viết theo lệnh ~sed~ như sau
#+NAME: enstring
#+BEGIN_SRC sh
sed 's/((?:[^.?\n]$|\n(?!.?$)))\n/$1 /g' FILENAME.ext
#+END_SRC
*** Căn chỉnh file timedot :emacs:hledger:
:PROPERTIES:
:CREATED: [2023-05-07 Sun 22:45]
:END:

File timedot là một file hledger đặc biệt, nó gồm nhiều kí tự dot "." và cũng nhiều dòng chú thích theo sau. Vì vậy nó có thể căn chỉnh bằng lệnh align-regexp trong emacs để nhìn trật tự hơn. Và vì thế cũng giúp cho người ghi tự do hơn mà không sợ mất đi tính trật tự của file, miễn là vẫn đảm bảo được cấu trúc ngữ pháp.

#+BEGIN_SRC emacs
M-x align-regexp RET [[:space:]]\. RET
M-x align-regexp RET [;] RET
M-x align-regexp RET \([0-9]+h\) RET
#+END_SRC
*** Công thức thay thế ngày SCHEDULED bằng PROPERTIES :orgmode:regex:

Khi tôi viết orgmode trên android, rất khó để viết đầy đủ các thủ tục tiêu chuẩn orgmode, vì vậy tôi sử dụng chức năng SCHEDULED để tạo lập 1 ngày tháng viết cho nhanh, sau này trên máy tính sẽ sử dụng chức năng *'Find and Replace'* có /regex/ để thay thế toàn bộ 1 lần. Cụ thể như sau

#+BEGIN_SRC find_and_replace
FIND: SCHEDULED: <(\d*-\d*-\d* \w*)>
REPLACE: :PROPERTIES:\n:CREATED: [$1]\n:END:
#+END_SRC

EDITED:[2023-02-10 Fri]
Tôi đã tạo được một snippet đáng tin cậy trong vscode về việc ngày tháng, nên nếu tôi không ở trong vscode để tạo snippet thì tôi có thể viết đoạn snippet đó theo nguyên mẫu, để sau này tôi tạo lại chúng sau bằng vscode. Từ nay nên tránh dùng SCHEDULED vì sẽ dễ gây nhầm lẫn đâu là schedule thật, đâu là chỉ để thay thế thời gian tạo mục. Và cũng để tận dụng chức năng schedule tốt hơn.

EDITED: [2023-05-11 Thu]
Công thức vim hoặc emacs subtitute cho thay đổi ở trên, lợi thế là nó one-liner, chỉ cần copy và paste vô là hoạt động hiệu quả

#+BEGIN_SRC vim
%s/SCHEDULED: <\(.*\)>/:PROPERTIES:\n:CREATED: [\1]\n:END:/gc
#+END_SRC
